### ISSUE TITLE
support for generating enunciate documentation using separately included jar for representation models

### ISSUE THREAD

**Issue by psin102** [stoicflame/enunciate-gradle#15]
Hi,

I have a gradle based Project A which contains the API Resources and a Project B containing the representation entities/models which I have included as a dependency jar in project A. My goal is to be able to read the javadoc documentation present in the Project B for the models and be able to show that in the enunciate swagger UI. For that, as far as i have understood, I should be providing the sourcepath() for the sources-jar/source files.

So far, I have tried to read the .java source files from Project B directly, include it as a fileTree and pass it to sourcepath(fileTreeObject) in the enunciate task closure. That has not worked for me and has given me following exception: 

could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/FILENAME.java]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
        at org.reflections.Reflections.scan(Reflections.java:236)
        at org.reflections.Reflections.scan(Reflections.java:203)
        at org.reflections.Reflections.<init>(Reflections.java:128)
        at com.webcohesion.enunciate.Enunciate.loadApiReflections(Enunciate.java:814)
        at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:565)
        at com.webcohesion.enunciate.gradle.EnunciateTask.run(EnunciateTask.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)

If anyone can help me correct course as to where I am going wrong here, that would be greatly appreciated. 

Thanks
PS

**Comment by stoicflame** [comment]
The java sourcepath isn't comprised of the list of `.java` files; it's comprised of a list of jars and/or directories that _contain_ `.java` files, like the classpath.

**Comment by psin102** [comment]
Hi thanks for pointing that out. So, I have tried doing the following in the gradle script :

```
def apiDocsDir = "$projectDir/api-docs"
def FileCollection collection = files()

tasks.enunciate {
    configFileName = "$projectDir/gradle/config/enunciate.xml"
    File enunciateDistDir = file(apiDocsDir)
    doFirst {
        enunciateDistDir.deleteDir()
        enunciateDistDir.mkdirs()
    }

    export("docs", enunciateDistDir)
    sourcepath(collection)
}

task addFiles() {
    doFirst {
        FileTree zipFiles = zipTree(System.getProperty("user.home") + "/path/to/local/maven/1.0.2-SNAPSHOT/common-entities-1.0.2-SNAPSHOT-sources.jar");
        
        zipFiles.each {
            collection = collection + files("${ it.getParent() }")
        }

        collection.each {
            println "${ it.absolutePath }" 
        }
    }
}

enunciate.dependsOn addFiles
```

In the collection print statement, it is picking up all the package directories where the representation models are correctly.

The jar that i am pointing to contains the source files with javadoc on the representation models. However, still the javadocs on those entities are not getting picked up in the UI. Is there something I am still missing in this script?

**Comment by jskov-jyskebank-dk** [comment]
You should probably have something like:

sourcepath(files(System.getProperty("user.home") + "/path/to/local/maven/1.0.2-SNAPSHOT/common-entities-1.0.2-SNAPSHOT-sources.jar"))

What you did was "exploding" the jar, which (I think) would mess up the package relationships.

**Comment by psin102** [comment]
Ah got it. I thought i should explode the jar so i can pick up hierarchical directories in packages.

But that worked for me. Thanks a ton!!!
